📖  Clarify restore hook init container priority
vmware-tanzu/velero pull request #3030
Opened 2020-10-21 20:56 UTC by ashish-amarnath

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

2020-10-26 18:26 UTC, nrb requested changes
We want a copy in `main` too, right?

2020-10-29 18:04 UTC, ashish-amarnath commented
Copied the change to main as well.
@nrb, @carlisia, @zubron, and @dsu-igeek PTAL.

2020-11-02 17:19 UTC, nrb approved these changes

2020-11-02 19:37 UTC, zubron approved these changes

2020-11-02 19:38 UTC, merged