🏃‍♂ Improve log message clarity
vmware-tanzu/velero pull request #3047
Opened 2020-10-27 19:24 UTC by ashish-amarnath

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Fixes: #3045

2020-10-29 18:04 UTC, ashish-amarnath commented
@nrb, @carlisia, @zubron, and @dsu-igeek PTAL.

2020-11-02 17:18 UTC, nrb requested changes

2020-11-02 17:18 UTC, nrb commented on pkg/controller/backup_storage_location_controller.go
> +	log.Info("Verifying availablity of backup storage locations.")
Given how often this runs, I think we should bump this down to debug. Otherwise, it just files the logs up, which makes parsing tough.

2020-11-02 17:18 UTC, nrb commented on pkg/controller/backup_storage_location_controller.go
> +		log.Debug("Validating backup storage location")
I would bump this up to Info since it happens less frequently than the verifying message, and can be useful to know that it's happening.

2020-11-02 17:43 UTC, nrb approved these changes

2020-11-02 19:02 UTC, carlisia reviewed
I am suggesting to use "validate/validating" every where in the controller and not interchange it with "verifying".

2020-11-02 19:02 UTC, carlisia commented on pkg/controller/backup_storage_location_controller.go
> +	log.Debug("Verifying availablity of backup storage locations.")
These new messages ARE better! One suggestion I have is to use "validation" everywhere. For example, in this case this message would be "Validating availability..."/

2020-11-02 19:02 UTC, carlisia commented on pkg/controller/backup_storage_location_controller.go
> +		log.Info("No backup locations needed to be verified")
```suggestion
		log.Info("No backup locations needed to be validated")
```

2020-11-02 20:20 UTC, zubron approved these changes
These messages are much clearer - thanks!

2020-11-02 20:21 UTC, zubron commented
This also fixes #2942.

2020-11-02 21:39 UTC, carlisia approved these changes
👍

2020-11-02 21:39 UTC, merged