pass annotations from scheduler to created backup
vmware-tanzu/velero pull request #3067
Opened 2020-11-11 08:11 UTC by funkycode

This should should pass annotations from scheduler to backup it creates

2020-11-13 17:31 UTC, nrb requested changes
Thanks for this contribution, I really appreciate it! I have one minor spelling change that I can see, but otherwise it looks good and I don't think there are any major ramifications.

2020-11-13 17:31 UTC, nrb commented on changelogs/unreleased/3067-funkycode
> +Pass annotations from schedluer to backup it creates the same way it is done for labels
`schedluer` -> `schedule`

2020-11-15 13:47 UTC, funkycode commented on changelogs/unreleased/3067-funkycode
> +Pass annotations from schedluer to backup it creates the same way it is done for labels
done

2020-11-19 18:55 UTC, ashish-amarnath approved these changes
LGTM!

2020-11-19 21:18 UTC, carlisia approved these changes
lgtm, thank you! 👍

2020-11-19 21:19 UTC, merged