feat: add delete sub-command to backup-location
vmware-tanzu/velero pull request #3073
Opened 2020-11-13 08:00 UTC by jenting

fixes #2168 

Add delete sub-command for BSL, list available sub-commands
```
velero backup-location delete <NAME>
```
or
```
velero delete backup-location <NAME>
velero delete backup-locations <NAME>
```

2020-11-19 18:10 UTC, carlisia requested changes
This is a great add, thank you! I tested it and it works, but I do have a request to use the new api calls.

2020-11-19 18:10 UTC, carlisia commented on pkg/cmd/cli/backuplocation/delete.go
> +			backupLocation, err := o.Client.VeleroV1().BackupStorageLocations(o.Namespace).Get(context.TODO(), name, metav1.GetOptions{})
I'd like to ask you to change the API calls to use the kubebuilder/runtimecontroller API. Here's an example:

https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/cli/backuplocation/get.go#L48-L61

2020-11-20 05:17 UTC, jenting commented
This is ready to be reviewed.

2020-11-20 16:32 UTC, carlisia approved these changes
I tested this and it works as intended. Thank you for this contribution!

2020-11-30 18:59 UTC, nrb approved these changes

2020-11-30 18:59 UTC, merged