Update links in volumesnapshotlocation.md
vmware-tanzu/velero pull request #3114
Opened 2020-11-26 10:57 UTC by nemeth

It seems that Hugo does not support reference-style links. See the generated doc at velero.io:
https://velero.io/docs/v1.5/api-types/volumesnapshotlocation/#parameter-reference

note: I haven't take the time yet to test it with a hugo build

2020-11-26 11:03 UTC, nemeth commented
related Hugo doc: https://gohugo.io/content-management/cross-references/

2020-11-26 20:10 UTC, zubron requested changes
Thanks for bringing this to our attention! As discussed in PR #2865, which added the table shortcode, we can't use reference links in shortcodes. The pages were updated to not use reference links but it looks like this is one that was missed!

Unfortunately, looking at the [preview build](https://deploy-preview-3114--velero.netlify.app/docs/main/api-types/volumesnapshotlocation/), I don't think we can use `relref` here. Instead, we can adjust our [table shortcode](https://github.com/vmware-tanzu/velero/blob/main/site/layouts/shortcodes/table.html#L8) to use use [`$.Page.RenderString`](https://gohugo.io/functions/renderstring/) instead of `markdownify` to ensure that it uses the [render-link render hook](https://github.com/vmware-tanzu/velero/blob/main/site/layouts/_default/_markup/render-link.html).  That would allow us to use inline relative markdown links (`[link text](../relative-link)`) in the table.

If you could update the table shortcode to use `RenderString`, and change the links to inline relative links that should fix it! The [same page in the 1.5 docs](https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/v1.5/api-types/volumesnapshotlocation.md) should also be updated as those are our "latest" docs.

You'll also need to [sign off any commits in this PR](https://github.com/vmware-tanzu/velero/pull/3114/checks?check_run_id=1458484952).

Thanks! :smile:

2020-12-04 14:03 UTC, zubron commented
Hi @nemeth! Are you still able to follow up on the suggested changes in this PR?

2020-12-10 00:39 UTC, nemeth commented
Thanks @zubron for the instructions!

The updated PR seems to be working with the changes you suggested:
https://deploy-preview-3114--velero.netlify.app/docs/main/api-types/backupstoragelocation/
https://deploy-preview-3114--velero.netlify.app/docs/main/api-types/volumesnapshotlocation/
https://deploy-preview-3114--velero.netlify.app/docs/v1.5/api-types/backupstoragelocation/
https://deploy-preview-3114--velero.netlify.app/docs/v1.5/api-types/volumesnapshotlocation/

2020-12-10 18:38 UTC, carlisia approved these changes
Thanks for this! 👍

2020-12-10 19:06 UTC, zubron approved these changes
Thank you for making the changes and noticing this issue!

2020-12-10 19:07 UTC, merged