Support fish shell completion
vmware-tanzu/velero pull request #3231
Opened 2021-01-12 14:55 UTC by jenting

As fish shell supported at [spf13/cobra v1.0.0 release](https://github.com/spf13/cobra/releases/tag/v1.0.0), adding fish shell completion for Velero.

The code change reference to https://github.com/spf13/cobra/blob/v1.1.1/shell_completions.md

2021-01-18 15:42 UTC, zubron requested changes
This is looking great. Thanks for updating the instructions as well. Just a couple of things that 
need to be changed before it can be merged. It's worth noting that this will fix #3281 (opened after this PR).

2021-01-18 22:35 UTC, jenting commented on pkg/cmd/cli/completion/completion.go
> +$ velero completion zsh > "${fpath[1]}/_yourprogram"
nice catch!

2021-01-21 22:57 UTC, zubron requested changes
Thanks for making the changes, @jenting! This looks good to me but there is a local file accidentally included in this. Once that's removed, it'll be ready to merge :)

2021-01-21 23:09 UTC, jenting commented on credentials-velero
> +[default]
oops, revert to more it.

2021-01-22 01:16 UTC, nrb approved these changes

2021-01-25 17:45 UTC, zubron approved these changes
Thanks!

2021-01-25 17:45 UTC, merged