Delete residual file caused by network interruption and so on. Fixes …
vmware-tanzu/velero pull request #3241
Opened 2021-01-13 10:08 UTC by Lighting-wings

…#3204

Signed-off-by: huangkai <huangkai76@huawei.com>

2021-01-19 19:32 UTC, dsu-igeek approved these changes
LGTM

2021-01-21 05:00 UTC, jenting requested changes
Please add a changelog for this PR, thank you.

2021-01-22 00:59 UTC, nrb commented on pkg/controller/restore_controller.go
I don't think so - that deletes the file before the `downloadToTempFile` function returns, even if there were no errors, so callers would never get an actual file.

2021-01-22 01:01 UTC, nrb submitted a review, later dismissed
@Lighting-wings The code looks correct to me, I think the only thing that's missing is a changelog file.

See https://velero.io/docs/v1.5/code-standards/#adding-a-changelog for how we use them.

2021-01-22 01:04 UTC, jenting commented on pkg/controller/restore_controller.go
You're right, thank you for the explanation.

2021-02-10 09:29 UTC, jenting commented
Ping @Lighting-wings

2021-04-16 00:15 UTC, dsu-igeek commented
@Lighting-wings Please add a changelog and we will merge this.  Thanks!

2021-06-02 20:40 UTC, zubron approved these changes

2021-06-02 20:41 UTC, merged