Add colors to describe command
vmware-tanzu/velero pull request #3275
Opened 2021-01-14 00:10 UTC by mike1808

* Add colors to describe backups/restore/schedules commands
* Make name in the output bold
* Disable colors via `--colorized` flag or if velero isn't in TTY

Fixes #1082 

If you have any other coloring suggestion please let us know.

cc @KauzClay

2021-01-21 04:48 UTC, jenting requested changes
Please run `make update` to fix CI failure. Thank you.

2021-01-22 02:46 UTC, nrb requested changes
This is really cool, thank you!

I have an additional request - can you add enabling/disabling this functionality into the Velero client config file, so folks can disable it for all runs? The file lives in `$HOME/.config/velero`, and [we have helper code for it that will need to read the key](https://github.com/vmware-tanzu/velero/blob/main/pkg/client/config.go). We should have existing code for the feature flags that allows for using the config file and command line flags.

2021-01-22 18:16 UTC, KauzClay commented
Hey @nrb ,

When you say you want it to be enabled/disabled via the config file, do you imagine it being part of "features", like this?
`{"features": "colors"}`

Or were you imagining a separate config field entirely, like this?
`{"features":"foo","colors":"off"}`

2021-01-22 19:49 UTC, nrb commented
> Or were you imagining a separate config field entirely, like this?

Yep! `features` are for feature flags that get passed from the client to the server to the plugins. Since this is purely clientside, I think it makes sense to be a dedicated field.

2021-01-22 19:53 UTC, carlisia approved these changes
This LGTM! 🎉

2021-01-22 19:54 UTC, carlisia commented
Hey @mike1808, your last commit was unsigned and so it's failing a check.

2021-01-26 13:30 UTC, jenting requested changes
I disabled the colorized in my $HOME/.config/velero/config.json as `{"colorized":"false"}`.
However, the color still existed for the command output.

2021-01-26 19:33 UTC, mike1808 commented
@jenting please use boolean values instead of strings.

2021-01-27 01:32 UTC, jenting commented
> @jenting please use boolean values instead of strings.

I think the problem comes when I running `velero client config set colorized=false`, the $HOME/.config/velero/config.json would be `{"colorized":"false"}`.

If I manually edit $HOME/.config/velero/config.json to  `{"colorized":false}`, the color is out.
But if I running `velero client config get`, if shows `colorized: %!s(bool=false)`.

2021-01-27 23:33 UTC, KauzClay commented
@jenting I see, is there a preference then for all config values to be strings then? We could change the value to a string and it could be on/off instead of true/false?

Or we could do some converting in the VeleroConfig struct to allow for the bool. Do you have a preference?

2021-01-28 02:03 UTC, jenting commented
> @jenting I see, is there a preference then for all config values to be strings then? We could change the value to a string and it could be on/off instead of true/false?

cc @nrb @carlisia @zubron any suggestion on this?

Personally, I'd prefer not to break the change (keep using the `strings` type).
Either "on"/"off" or "true"/"false" is fine to me.

> 
> Or we could do some converting in the VeleroConfig struct to allow for the bool. Do you have a preference?

2021-01-29 22:04 UTC, KauzClay commented
@jenting okay, you should be able to use `velero client config set colorized=false` and see that the color doesn't show now.

As a note, we made it so that the command line flag `--colorized=true` will override whatever is in the client config.

2021-01-30 05:42 UTC, jenting commented
Thank you. Two comments left:
1. It'd be better to add doc for this nice feature
2. Please fix the conflicting files

2021-02-01 19:32 UTC, KauzClay commented
Hi @jenting , I think we resolved the conflicting files. As for the doc, we weren't sure where to put this information. We opted for `site/content/docs/main/customize-installation.md`, since we saw other references to client config there. If that isn't okay, could you please explain where you were envisioning this documentation to live?

2021-02-02 13:53 UTC, jenting commented
> We opted for `site/content/docs/main/customize-installation.md`, since we saw other references to client config there.

I'm okay to put it here.

I saw the last two commits had signed off, but the CI failed at DCO check, strange 🤔

2021-02-02 14:35 UTC, carlisia commented on site/content/docs/main/customize-installation.md
> +Note, that if you specify `--colorized=true` as a CLI option it will override
```suggestion
Note that if you specify `--colorized=true` as a CLI option it will override
```

2021-02-02 14:39 UTC, jenting commented on site/content/docs/main/customize-installation.md
> +Velero CLI uses colored output for some commands, such as `velero desribe`. If
```suggestion
Velero CLI uses colored output for some commands, such as `velero describe`. If
```

2021-02-02 14:39 UTC, carlisia commented
@jenting thanks for testing this.

@KauzClay this looks great and ready to merge as far as I'm concerned except for:
- the biggest/tinniest nit pick ever (see above)
- we need to make the DCO check pass

Thank you.

2021-02-03 21:01 UTC, nrb commented
@KauzClay Once you make the two changes asked for, please sign the commits as shown at https://github.com/vmware-tanzu/velero/pull/3275/checks?check_run_id=1809391225

2021-02-08 23:06 UTC, KauzClay commented
Ah, sorry about messing up the sign off thing. Hopefully I got it this time?

2021-02-09 00:49 UTC, jenting approved these changes
LGTM, thank you.

2021-02-09 16:38 UTC, carlisia approved these changes

2021-02-09 16:39 UTC, merged