Don't run CI checks if only the site changed
vmware-tanzu/velero pull request #3438
Opened 2021-02-09 19:20 UTC by nrb

Also include the github directory to enable faster iteration on GitHub
actions

Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

2021-02-09 23:24 UTC, carlisia submitted a review, later dismissed
Awesome 🎉

2021-02-10 00:06 UTC, jenting commented
Related to https://github.com/vmware-tanzu/velero/issues/2557

2021-02-10 01:09 UTC, jenting commented
This needs to address the conflicts.

2021-02-10 18:04 UTC, nrb commented
Conflicts fixed!

2021-02-10 18:25 UTC, zubron requested changes
This is great, thanks @nrb! There's a single fix needed in the changelog check action where code checkout is being called twice.

2021-02-10 18:25 UTC, zubron commented on .github/workflows/pr-changelog-check.yml
> +      - name: Check out the code
This step is being included twice now.

2021-02-10 21:34 UTC, jenting approved these changes

2021-02-10 22:38 UTC, zubron approved these changes

2021-02-10 22:48 UTC, zubron commented
Hmm, I don't know if this will work in it's current state. We have branch protection for main that requires that the `Run CI` check must pass before merging, but this will now never run on PRs like this. I don't know if there is a way to make the checks conditional. Looks like it's an open request in the GitHub community: https://github.community/t/feature-request-conditional-required-checks/16761

2021-02-10 23:23 UTC, nrb commented
> We have branch protection for main that requires that the Run CI check must pass before merging, but this will now never run on PRs like this.

Oof, you're right. So we'd need to make the change in the Run CI workflow to check for this. I _think_ we can do that.

2021-02-10 23:26 UTC, nrb commented
I'm going to close this and look into an alternate approach. I have another idea for cleaning up some of the CRD testing anyway, so that they're consolidated into 1 file.

2021-02-10 23:26 UTC, closed without merging