Prefer conditional waiting over magic sleep
vmware-tanzu/velero pull request #3527
Opened 2021-03-05 08:49 UTC by ashish-amarnath

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-03-05 21:07 UTC, nrb submitted a review, later dismissed

2021-03-05 23:05 UTC, ashish-amarnath commented
Partially addresses #3532

2021-03-09 19:36 UTC, zubron requested changes
This is great, thank you @ashish-amarnath! I just have one request to also wait for the namespace deletion at the end of `RunKibishiiTests`.

2021-03-09 19:38 UTC, ashish-amarnath commented on changelogs/unreleased/3527-ashish-amarnath
> +Prefer conditional waiting over magic sleep.
This IMO is a bug fix

2021-03-09 21:15 UTC, carlisia commented on changelogs/unreleased/3527-ashish-amarnath
> +Prefer conditional waiting over magic sleep.
What @zubron said. The CI check is for all feature changes which do need a changelog so we can compile them later for the release notes. Everything else gets labeled nochangelogneeded, document, or website to skip the CI check.

Adding changelogs for tests only adds unnecessary clutter to what will need to be release notes later.

2021-03-09 21:22 UTC, carlisia commented on changelogs/unreleased/3527-ashish-amarnath
> +Prefer conditional waiting over magic sleep.
I could swear I wrote the heuristics for what PR type gets what label, but looked everywhere and didn't find it.

2021-03-09 21:23 UTC, ashish-amarnath commented
The change log file has now been removed!

________________________________
From: Carlisia Thompson <notifications@github.com>
Sent: Tuesday, March 9, 2021 1:22:27 PM
To: vmware-tanzu/velero <velero@noreply.github.com>
Cc: Ashish Amarnath <ashisham@vmware.com>; Mention <mention@noreply.github.com>
Subject: Re: [vmware-tanzu/velero] Prefer conditional waiting over magic sleep (#3527)


@carlisia commented on this pull request.

________________________________

In changelogs/unreleased/3527-ashish-amarnath<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fvelero%2Fpull%2F3527%23discussion_r590728595&data=04%7C01%7Cashisham%40vmware.com%7C8a1ad86ce4cc4f8e1e0a08d8e34170bb%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C1%7C0%7C637509217491295588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mo4kxx0yQN0hhh66srG2zUOBcWwu66k7AkYMr7bzSdk%3D&reserved=0>:

> @@ -0,0 +1 @@
+Prefer conditional waiting over magic sleep.


I could swear I wrote the heuristics for what PR type gets what label, but looked everywhere and didn't find it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmware-tanzu%2Fvelero%2Fpull%2F3527%23discussion_r590728595&data=04%7C01%7Cashisham%40vmware.com%7C8a1ad86ce4cc4f8e1e0a08d8e34170bb%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C1%7C0%7C637509217491305587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jFxmBDalwaGFul6e7MEDcRrWfIik%2FTGPlAEN4R15n0M%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFOQASQO26N3ZG33DJHPJJ3TCZ7QHANCNFSM4YU2BWNA&data=04%7C01%7Cashisham%40vmware.com%7C8a1ad86ce4cc4f8e1e0a08d8e34170bb%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C1%7C0%7C637509217491305587%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uM5GIUkPL0cBwHCvFG6t5cYKia7G%2FLOPO6sRW%2FrHreQ%3D&reserved=0>.

2021-03-09 21:30 UTC, zubron approved these changes

2021-03-09 21:32 UTC, carlisia approved these changes
This looks good 👍

2021-03-09 21:32 UTC, merged