Wait for velero deployment to be ready
vmware-tanzu/velero pull request #3879
Opened 2021-06-17 14:49 UTC by Divya063

Signed-off-by: Divya Rani <drani@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

Running `velero install` does not wait for velero to be healthy and does not report errors. The changes fix this issue. 

# Does your change fix a particular issue?
Yes

Fixes #3861 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-06-17 15:37 UTC, Divya063 commented
/kind changelog-not-required

2021-06-18 01:13 UTC, jenting reviewed
Could we wait for restic DaemonSet if `--use-restic` be passed?
Besides that, the changelog is required. Thank you.

2021-06-18 09:40 UTC, Divya063 commented
@jenting Sure, I see a [wait flag](https://github.com/vmware-tanzu/velero/blob/d871370c1e7e265acac418d70e96fa5182c9fb7f/pkg/cmd/cli/install/install.go#L281) for that purpose ( for both velero deployment and restic Daemonset), I was wondering shouldn't it be a default behaviour?

2021-06-18 09:49 UTC, jenting commented
Or perhaps the original usage did not pass the `--wait` flag?

2021-06-18 11:32 UTC, Divya063 commented
@jenting  I was thinking if we could remove the wait flag itself, because anyway we would be waiting for both velero deployment and restic Daemonset (after I make the change)?

2021-06-18 11:35 UTC, jenting commented
Please do not break backward compatible.

2021-06-18 12:26 UTC, Divya063 commented
@jenting I have made the changes. Thanks!

2021-06-19 12:42 UTC, jenting requested changes
I'd suggest checking the original issue's bug _or_ request, then find an appropriate way to fix it. Thank you.

2021-06-19 12:42 UTC, jenting commented on pkg/cmd/cli/install/install.go
> +
Isn't it duplicate? https://github.com/vmware-tanzu/velero/blob/002bc56ad360c6b3604bc7c9508b7252ebe6f53e/pkg/cmd/cli/install/install.go#L294-L299

2021-09-10 21:31 UTC, closed without merging