Add the design for `velero debug`
vmware-tanzu/velero pull request #3973
Opened 2021-07-18 11:01 UTC by reasonerjt

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-07-20 18:41 UTC, sseago requested changes
Looks good overall -- just a suggestion for a small change -- to take the namespace option into account when calling `velero version`.

2021-07-21 09:35 UTC, reasonerjt commented on design/velero-debug.md
> +capture_local(cmd="velero version")
Good point! Thanks @sseago 

Fixed in https://github.com/vmware-tanzu/velero/pull/3973/commits/309e8ac5c0615b733a15e7f092474e5d8254995b

2021-07-21 13:55 UTC, sseago approved these changes

2021-07-22 05:29 UTC, dsu-igeek approved these changes
LGTM

2021-07-22 05:29 UTC, merged