adding rbac test to e2e tests
vmware-tanzu/velero pull request #3982
Opened 2021-07-25 23:57 UTC by jaidevmane

Signed-off-by: Jai Subash Devmane <jdevmane@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-07-27 00:21 UTC, jaidevmane commented
All checks passed. Ready to review.

2021-08-14 00:12 UTC, dsu-igeek requested changes
Looks like this needs to be rebased.  Would you split up the createNamespaceAndRbac into some smaller functions - it seems like this is only useful for this case, so it's not very common.

2021-08-14 00:12 UTC, dsu-igeek commented on test/e2e/common.go
> +// createNamespaceAndRbac creates a kubernetes namespace, service account, clusterrole, and clusterrolebinding
Let's break this into separate functions.  This is not very re-usable, everything needs to be done together.

2021-09-01 02:38 UTC, ywk253100 commented
Similar to https://github.com/vmware-tanzu/velero/pull/3944, let's expand the existing `Basic` test case to include the RBAC resources.
Both of these two PRs need some adjustment of the `Basic` test case before expanding it, see https://github.com/vmware-tanzu/velero/pull/3944#issuecomment-909818616

2021-09-29 01:42 UTC, dsu-igeek commented
Leaving this open until #4099 is addressed

2021-12-17 03:20 UTC, qiuming-best commented
I'll keep going on the works on #4455, so I closed

2021-12-17 03:20 UTC, closed without merging