Control the name of backup used in E2E test to avoid issue on vSphere
vmware-tanzu/velero pull request #3985
Opened 2021-07-26 02:23 UTC by ywk253100

The backup name must be no more than 63 characters otherwise we'll get error on vSphere platform:

Failed to create snapshot record: Snapshot.backupdriver.cnsdp.vmware.com \"snap-8945e7df-069e-4f56-aeb5-75b1dd87547f\" is invalid: metadata.labels: Invalid value: \"backup-bsl-e7a1d0f3-2f29-4d80-9184-6214dac91d96-e7a1d0f3-2f29-4d80-9184-6214dac91d96\": must be no more than 63 characters"

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-07-26 07:24 UTC, jenting commented on test/e2e/backup_test.go
> +				// append the UUID for the name of backup with the default BSL and as the name of additional BSL already contains
nit:
```suggestion
                              // Append the UUID for the name of backup with the default BSL and as the name of additional BSL already contains
```

2021-07-26 13:02 UTC, ywk253100 commented on test/e2e/backup_test.go
> +				// append the UUID for the name of backup with the default BSL and as the name of additional BSL already contains
Updated, thanks

2021-07-26 14:05 UTC, jenting submitted a review, later dismissed

2021-07-28 05:55 UTC, dsu-igeek requested changes
Please put a comment in here as to WHY we're limiting the length of the name and a note that we should remove it when the vSphere plugin is fixed.

2021-07-28 06:45 UTC, dsu-igeek approved these changes
LGTM - thanks!

2021-07-28 07:28 UTC, jenting approved these changes

2021-07-28 07:28 UTC, merged