Restic Backup: Add check if Pod is successful or failed for emptyDir.…
vmware-tanzu/velero pull request #3993
Opened 2021-07-27 11:25 UTC by mahaupt

# Summary
I added a check to exclude restic backups for emptyDirs on stopped but unremoved pods (successful / failed).
Emptydirs are only guaranteed to persist on running / crashing pods.  

https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

Please let me know if I shall add a changelog / documentation for this small bugfix.

# Does your change fix a particular issue?

Fixes #3812

# Please indicate you've done the following:

- [ x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2021-07-27 15:58 UTC, sseago requested changes
Looks good, but since it's a bug fix, it will need a changelog file.

2021-07-28 07:20 UTC, mahaupt commented
I just added the missing changelog file

2021-07-28 21:52 UTC, sseago approved these changes

2021-08-04 04:52 UTC, jenting approved these changes

2021-08-04 04:53 UTC, merged

2022-07-11 10:57 UTC, Ankita5892 commented
my pods are running for openshift all namespace still its give issue for only pod's which has emptyDir its not failing but its stuck like never ending backup 
any one has idea

2022-07-11 10:59 UTC, mahaupt commented
Check if the velero pod has enough resources and is not running out of memory