Read Availability zone from nodeAffinity requirements
vmware-tanzu/velero pull request #4334
Opened 2021-11-11 08:35 UTC by reasonerjt

2021-11-11 15:37 UTC, sseago requested changes
Other than adding one more arg to zoneFromPVNodeAffinity this looks good.

2021-11-11 15:37 UTC, sseago commented on pkg/backup/item_backupper.go
> +			k, pvFailureDomainZone = zoneFromPVNodeAffinity(pv, awsEbsCsiZoneKey, azureCsiZoneKey, zoneLabel)
In my current cluster using ebs volumes, the nodeAffinity uses "failure-domain.beta.kubernetes.io/zone" in its `required.nodeselectorterms.matchexpressions` field. While this particular volume will be caught via the zoneLabelDeprecated *label* check, for completeness we should probably add `zoneLabelDeprecated` to the `zoneFromPVNodeAffinity` args.

2021-11-15 12:31 UTC, jenting commented
Is this PR superseded by #4338?

2021-11-15 16:01 UTC, reasonerjt commented
@jenting it is. I'm closing this PR

2021-11-15 16:01 UTC, closed without merging