add solution for backups stuck InProgress
vmware-tanzu/velero pull request #4392
Opened 2021-11-23 14:26 UTC by dirsigler

Signed-off-by: Dennis Irsigler <dennis.irsigler@metro-markets.de>

Thank you for contributing to Velero!

# Please add a summary of your change
This change adds a section to the troubleshooting guide to inform about a common problem with backups stuck InProgress for bigger cluster/backup setups.

# Does your change fix a particular issue?
No.

Fixes #(issue)
https://github.com/vmware-tanzu/velero/issues/4003

/kind changelog-not-required

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [X] Updated the corresponding documentation in `site/content/docs/main`.

2021-11-24 01:00 UTC, dsu-igeek requested changes
This doesn't actually document how to handle a stuck backup, it documents how to increase the memory limit to avoid Velero pod restart.  Please rewrite to show this is a solution for out of memory errors and how to recognize out of memory errors.

2021-11-30 21:29 UTC, a-mccarthy reviewed
Thanks for submitting @dirsigler! I have a few small comments

2021-11-30 21:29 UTC, a-mccarthy commented on site/content/docs/main/troubleshooting.md
> +This issue can lead to a restart of the Velero Pod which results to the `InProgress` state.
I think 'state' should be 'phase' here to match the Velero terminology

2021-11-30 21:29 UTC, a-mccarthy commented on site/content/docs/main/troubleshooting.md
> +This issue can lead to a restart of the Velero Pod which results to the `InProgress` state.
Can you also make it more clear that the InProgress state does not go away?

2021-11-30 21:29 UTC, a-mccarthy commented on site/content/docs/main/troubleshooting.md
> +It may happen that the Velero process hits memory limits when backing up big system with a lot of resources.
nit: i think you are missing 'a' in this sentence 'when backing up **a** big system with a lot of resources.'

2022-02-13 11:05 UTC, closed without merging