Add CloudCasa to "Adopters of Velero" section on velero.io
vmware-tanzu/velero pull request #4588
Opened 2022-01-27 07:45 UTC by kkothule

Thank you for contributing to Velero!

# Please add a summary of your change

- Added CloudCasa logo
- Added description of CloudCasa and its integration with Velero

Signed-off-by: Kiran Kothule from Catalogic Software <kkothule@catalogicsoftware.com>

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2022-01-27 17:21 UTC, kaovilai requested changes

2022-01-27 17:21 UTC, kaovilai commented on ADOPTERS.md
> +**[CloudCasa][103]**
![image](https://user-images.githubusercontent.com/11228024/151410400-93c4780a-c895-4cf7-af10-d5d8b96893a7.png)

Might want to check the resulting formatting. Shouldn't there be a new line before org name?

2022-01-31 06:43 UTC, kkothule commented
@kaovilai please review the changes

2022-01-31 07:43 UTC, kaovilai approved these changes
Not a maintainer but lgtm

2022-01-31 12:37 UTC, kkothule commented
Thanks, @kaovilai, Please help me in getting the final review from the maintainer, Whom should I assign PR for review or if you can assign it to someone

2022-01-31 12:48 UTC, kaovilai commented
Technically it's already assigned. Just wait a bit.

2022-02-14 19:25 UTC, a-mccarthy commented
Thanks for submitting this @kkothule! This lgtm, tagging @jonasrosland and @OrlinVasilev for review as well

2022-02-14 19:32 UTC, jonasrosland commented
This LGTM, thank you @kkothule !

2022-02-14 20:25 UTC, sseago approved these changes

2022-02-15 05:17 UTC, kkothule commented
Thank You @jonasrosland and @a-mccarthy, Can we merge this to the main branch?

2022-02-15 16:56 UTC, OrlinVasilev approved these changes
LGTM :)

2022-02-17 00:57 UTC, merged

2022-02-18 09:47 UTC, kkothule commented
Thanks @jenting