Add supported versions statment to support process page
vmware-tanzu/velero pull request #4903
Opened 2022-05-09 18:08 UTC by a-mccarthy

Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change
This adds a note about the supported versions to the support process page

# Does your change fix a particular issue?

Fixes https://github.com/vmware-tanzu/velero/issues/4285

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

2022-05-09 18:17 UTC, eleanor-millman commented on site/content/docs/main/support-process.md
> +Velero provides best effort support through the process on this page for the current version of Velero and n-1 Velero version, including all patch release in the supported minor releases. For example
should it be "all patch releases"?

2022-05-09 18:18 UTC, eleanor-millman requested changes
LGTM, just want to see release -> to releases. Thanks!

2022-05-09 18:19 UTC, a-mccarthy commented on site/content/docs/main/support-process.md
> +Velero provides best effort support through the process on this page for the current version of Velero and n-1 Velero version, including all patch release in the supported minor releases. For example
fixed!

2022-05-09 18:20 UTC, eleanor-millman approved these changes

2022-05-18 07:29 UTC, reasonerjt approved these changes

2022-05-18 07:30 UTC, merged