Make velero completion zsh command output can be used by `source` com…
vmware-tanzu/velero pull request #4914
Opened 2022-05-16 03:32 UTC by blackpiglet

…mand.

Signed-off-by: Xun Jiang <jxun@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #4912 

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2022-05-16 14:25 UTC, sseago requested changes

2022-05-17 02:03 UTC, blackpiglet commented on pkg/cmd/cli/completion/completion.go
> +				// cobra not support zsh completion ouptput used by source command
Thanks. Modified.

2022-05-18 03:00 UTC, reasonerjt approved these changes

2022-05-18 11:41 UTC, blackpiglet commented
@sseago 
Scott, could you PTAL?

2022-05-23 14:05 UTC, sseago approved these changes

2022-05-23 14:05 UTC, merged