Clean backups after each test
vmware-tanzu/velero pull request #5210
Opened 2022-08-15 07:50 UTC by danfengliu

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2022-08-18 07:21 UTC, blackpiglet approved these changes

2022-08-18 13:47 UTC, sseago requested changes
One codespell failure from this PR, also rebase PR to pull in the merged fix from earlier today which will resolve the other codespell failures.

2022-08-18 13:47 UTC, sseago commented on test/e2e/resource-filtering/exclude_label.go
> +	// These 2 labels for resouces to be included
Codespell failure s/resouces/resources

2022-08-19 01:25 UTC, danfengliu commented on test/e2e/resource-filtering/exclude_label.go
> +	// These 2 labels for resouces to be included
Thanks, it's fixed.

2022-08-19 01:30 UTC, blackpiglet approved these changes

2022-08-19 01:50 UTC, qiuming-best approved these changes

2022-08-19 14:02 UTC, sseago approved these changes

2022-08-19 14:02 UTC, merged