Add warning/error result to cmd `velero backup describe`
vmware-tanzu/velero pull request #5916
Opened 2023-02-24 10:22 UTC by allenxu404

Thank you for contributing to Velero!

# Please add a summary of your change
- Add `backupResult`type to downloadRequest crd
- Add warning/error result to cmd `velero backup describe`
# Does your change fix a particular issue?

Fixes #5200

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-02-25 20:59 UTC, sseago commented
Note that https://github.com/vmware-tanzu/velero/pull/5576 was recently merged that added backup warnings/errors to object store. From a quick look, it seems that this PR allows the newly-added results to be displayed via the backup describer. Let me know if I'm understanding the purpose here correctly and whether this PR adds onto that recently-merged result. In any case, I'll try to give this PR a more detailed look over the next week.

2023-02-28 02:50 UTC, allenxu404 commented
@sseago Yes, this PR adds warning/error data to the output of backup describer and structured describer(a new describer developed in v1.11, which is used to display output in json format, please refer to #5865 for more info) based on #5576.

2023-03-02 06:54 UTC, anshulahuja98 commented
Thank you for this contribution @allenxu404 , I had intended to add this support post #5576 
If possible, please try to share sample CLI outputs of this work. 

I will meanwhile also review the PR further

2023-03-02 09:09 UTC, allenxu404 commented
@anshulahuja98 Here are some CLI output formats:

If errors/warnings exist  && backupResults json not exists
```
velero backup describe myBackup:
Name: myBackup
...
Errors:    1
Warnings:  1
...

velero backup describe myBackup -o json:
{
    "name": "myBackup",
    "errors": {
        "count": 1
    },
    "warnings": {
        "count": 1
    },
    ...
}
```

If errors/warnings exist  && backupResults json exists
```
velero backup describe myBackup:
Name: myBackup
...
Errors:
  Velero:     <none>
  Cluster:   cluster error
  Namespaces: <none>

Warnings:
  Velero:     <none>
  Cluster:   cluster warning
  Namespaces: <none>
...

velero backup describe myBackup -o json:
{
    "name": "myBackup",
    "errors": {
        "cluster": [
            "cluster error"
        ],
        "namespace": [],
        "velero": []
    },
    "warnings": {
        "cluster": [
            "cluster warning"
        ],
        "namespace": [],
        "velero": []
    },
    ...
}
```

2023-03-03 02:55 UTC, allenxu404 commented
@sseago Do you have some time to review this PR?

2023-03-06 11:43 UTC, allenxu404 commented
> 



> not very clear to me how this will end up looking like
> 
> for example for namespaced errors are you splitting the key/value pair to represent better?

Yes,  the format is consistent with `restore describe`. Actually they share the same func.

2023-03-06 11:56 UTC, anshulahuja98 commented
I realized that later @allenxu404, and redacted that comment. Good that the function was reused.
I made some small nitpick comments, you can go through them. Otherwise the PR  LGTM.

We would need maintainers to signoff. Good to see closure on the backupresults approach in a more user friendly way.
Thank you for your contribution.

2023-03-06 13:03 UTC, anshulahuja98 requested changes

2023-03-06 23:18 UTC, sseago approved these changes

2023-03-07 02:53 UTC, allenxu404 commented on pkg/cmd/util/output/backup_describer.go
> +	if backup.Status.Warnings == 0 && backup.Status.Errors == 0 {
I might miss something but Indent here seems good to me. What problem are you seeing?

2023-03-07 02:53 UTC, allenxu404 commented on pkg/cmd/util/output/backup_describer.go
> +	if err := downloadrequest.Stream(ctx, kbClient, backup.Namespace, backup.Name, velerov1api.DownloadTargetKindBackupResults, &buf, downloadRequestTimeout, insecureSkipTLSVerify, caCertPath); err == d
Make sense.

2023-03-08 19:19 UTC, sseago submitted a review, later dismissed

2023-03-15 07:50 UTC, ywk253100 approved these changes

2023-03-15 08:46 UTC, allenxu404 commented
@sseago Can you give me another review? I merged the main branch and solved the conflicts.

2023-03-16 02:27 UTC, Lyndon-Li approved these changes

2023-03-16 02:28 UTC, merged