Make E2E test adopt vSphere CSI version update
vmware-tanzu/velero pull request #6034
Opened 2023-03-26 12:59 UTC by blackpiglet

Thank you for contributing to Velero!

# Please add a summary of your change
E2E test can read VC credential secret according to the vSphere CSI driver version.
This fix is needed to run E2E test on TKG environment.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-03-28 02:17 UTC, blackpiglet commented
Found the fact that the vSphere plugin's image paths on TKG and OSS are different.
On TKG, it's `tkg/csi/vsphere-block-csi-driver`. On OSS, it's `cloud-provider-vsphere/csi/release/driver`.
To make things more complicated, TKG's vSphere CSI driver's image tag is in sha256 format.
As a result, I think it's not worth determining where to read the VC credential depending on the vSphere CSI driver version.
Just read from `kube-system` namespace first, if not found, read from `vmware-system-csi` namespace. Not found in both namespaces, raise error.

2023-03-28 03:20 UTC, blackpiglet commented
Test passed. This is the result.

```
kubo@G4cTbeLyyJjzp:~/velero$ GOPATH=$HOME/go CLOUD_PROVIDER=vsphere CREDS_FILE=$HOME/minio-creds BSL_CONFIG=region=minio,s3ForcePathStyle=true,s3Url=http://10.191.193.199:9000 BSL_BUCKET=velero VSL_CONFIG=region=minio VELERO_VERSION=v1.9.6 VELERO_NAMESPACE=velero REGISTRY_CREDENTIAL_FILE=$HOME/.docker/config.json VELERO_IMAGE=projects-stg.registry.vmware.com/tkg/velero/velero:v1.9.6_vmware.1 RESTIC_HELPER_IMAGE=projects-stg.registry.vmware.com/tkg/velero/velero-restic-restore-helper:v1.9.6_vmware.1 GINKGO_FOCUS=ClusterResource PLUGINS=projects-stg.registry.vmware.com/tkg/sandbox/velero/velero-plugin-for-aws:v1.5.4_vmware.1,projects-stg.registry.vmware.com/tkg/velero/velero-plugin-for-vsphere:v1.4.2_vmware.1 VERSION=v1.9.6 KIBISHII_DIRECTORY=$HOME/kibishii/kubernetes/yaml/ make test-e2e
GOOS=linux \
GOARCH=amd64 \
VERSION=v1.9.6 \
REGISTRY=velero \
PKG=github.com/vmware-tanzu/velero \
BIN=velero \
GIT_SHA=2ff46f95396453565a7a5fe25c8e528b2d577c8a \
GIT_TREE_STATE=dirty \
OUTPUT_DIR=$(pwd)/_output/bin/linux/amd64 \
./hack/build.sh
make -e VERSION=v1.9.6 -C test/e2e run
make[1]: Entering directory '/home/kubo/velero/test/e2e'
go install github.com/onsi/ginkgo/ginkgo@v1.16.5
Using credentials from /home/kubo/minio-creds
Using bucket velero to store backups from E2E tests
Using cloud provider vsphere
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
STEP: Create test client instance
Running Suite: E2e Suite
========================
Random Seed: 1679973299
Will run 3 of 32 specs

SSSSSSSSSSSSSSS
------------------------------
[Basic][ClusterResource] Backup/restore of cluster resources
  Should be successfully backed up and restored including annotations
  /home/kubo/velero/test/e2e/test/test.go:133
configvSpherePlugin: WaitForConfigMapComplete
Running cmd "/home/kubo/velero/test/e2e/../../_output/bin/linux/amd64/velero install --namespace velero --image projects-stg.registry.vmware.com/tkg/velero/velero:v1.9.6_vmware.1 --use-restic --provider aws --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.191.193.199:9000 --bucket velero --secret-file /home/kubo/minio-creds --snapshot-location-config region=minio --plugins projects-stg.registry.vmware.com/tkg/sandbox/velero/velero-plugin-for-aws:v1.5.4_vmware.1,projects-stg.registry.vmware.com/tkg/velero/velero-plugin-for-vsphere:v1.4.2_vmware.1 --dry-run --output json --crds-only"
Applying velero CRDs...
customresourcedefinition.apiextensions.k8s.io/backups.velero.io created
customresourcedefinition.apiextensions.k8s.io/backupstoragelocations.velero.io created
customresourcedefinition.apiextensions.k8s.io/deletebackuprequests.velero.io created
customresourcedefinition.apiextensions.k8s.io/downloadrequests.velero.io created
customresourcedefinition.apiextensions.k8s.io/podvolumebackups.velero.io created
customresourcedefinition.apiextensions.k8s.io/podvolumerestores.velero.io created
customresourcedefinition.apiextensions.k8s.io/resticrepositories.velero.io created
customresourcedefinition.apiextensions.k8s.io/restores.velero.io created
customresourcedefinition.apiextensions.k8s.io/schedules.velero.io created
customresourcedefinition.apiextensions.k8s.io/serverstatusrequests.velero.io created
customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io created
Waiting velero CRDs ready...
customresourcedefinition.apiextensions.k8s.io/backups.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/backupstoragelocations.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/deletebackuprequests.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/downloadrequests.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/podvolumebackups.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/podvolumerestores.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/resticrepositories.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/restores.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/schedules.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/serverstatusrequests.velero.io condition met
customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io condition met
Running cmd "/home/kubo/velero/test/e2e/../../_output/bin/linux/amd64/velero install --namespace velero --image projects-stg.registry.vmware.com/tkg/velero/velero:v1.9.6_vmware.1 --use-restic --provider aws --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.191.193.199:9000 --bucket velero --secret-file /home/kubo/minio-creds --snapshot-location-config region=minio --plugins projects-stg.registry.vmware.com/tkg/sandbox/velero/velero-plugin-for-aws:v1.5.4_vmware.1,projects-stg.registry.vmware.com/tkg/velero/velero-plugin-for-vsphere:v1.4.2_vmware.1 --dry-run --output json"
image pull secret "image-pull-secret" set for velero serviceaccount
the restic restore helper image is set by the configmap "restic-restore-action-config"
Running cmd "/home/kubo/path/kubectl apply -f -"
customresourcedefinition.apiextensions.k8s.io/backups.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/backupstoragelocations.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/deletebackuprequests.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/downloadrequests.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/podvolumebackups.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/podvolumerestores.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/resticrepositories.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/restores.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/schedules.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/serverstatusrequests.velero.io unchanged
customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io unchanged
Warning: resource namespaces/velero is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
namespace/velero configured
clusterrolebinding.rbac.authorization.k8s.io/velero created
serviceaccount/velero created
secret/cloud-credentials created
backupstoragelocation.velero.io/default created
volumesnapshotlocation.velero.io/default created
deployment.apps/velero created
Warning: would violate PodSecurity "baseline:v1.24": hostPath volumes (volume "host-pods")
daemonset.apps/restic created
secret/image-pull-secret created
configmap/restic-restore-action-config created
Waiting for Velero deployment to be ready.
Waiting for Velero restic daemonset to be ready.
Velero is installed and ready to be tested in the velero namespace! ⛵
Running test case Backup/restore namespace annotation test
velero cmd =/home/kubo/velero/test/e2e/../../_output/bin/linux/amd64/velero create --namespace velero backup backup-namespace-annotationsac4dbc18-799f-4126-82da-6 [...]

2023-03-29 00:05 UTC, ywk253100 approved these changes

2023-03-29 00:16 UTC, danfengliu requested changes

2023-03-29 00:16 UTC, danfengliu commented on test/e2e/util/velero/install.go
> +			secret, err = GetSecret(c, VSphereCSIControllerNamespace, "vsphere-config-secret")
Missing return here.

2023-03-29 00:16 UTC, danfengliu commented on test/e2e/util/velero/install.go
> +	return
Missing secret and error in return here.

2023-03-29 00:23 UTC, danfengliu approved these changes

2023-03-29 00:25 UTC, merged

2023-07-11 02:52 UTC, danfengliu commented
Fixed issue: #5998