Allow updated resource version
vmware-tanzu/velero pull request #6499
Opened 2023-07-14 09:38 UTC by danielkucera

Thank you for contributing to Velero!

# Please add a summary of your change

This change will allow changing the object apiVersion using a plugin

# Does your change fix a particular issue?

Fixes #6498 

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-07-14 09:38 UTC, danielkucera commented
/kind changelog-not-required

2023-07-18 14:22 UTC, sseago requested changes
Looks good, but a minor request -- add a comment above the new getResourceClient call giving the reason for grabbing it again, otherwise someone reading through this later may not realize that  the reason for calling it a second time is that the version of `obj` may have changed during plugin calls.

2023-07-20 18:07 UTC, danielkucera commented
@sseago , please check updated revision. Thank you.

2023-07-21 20:50 UTC, sseago approved these changes

2023-07-21 21:10 UTC, shubham-pampattiwar approved these changes

2023-08-10 02:44 UTC, merged