Deal with PartiallyFailed orphaned backups as well as Completed ones
vmware-tanzu/velero pull request #6649
Opened 2023-08-14 17:39 UTC by sseago

Fixes https://github.com/vmware-tanzu/velero/issues/6648

Thank you for contributing to Velero!

When cleaning up orphaned backups, include PartiallyFailed with Completed, since they are treated equivalently by the rest of backup sync.

# Does your change fix a particular issue?

Fixes #6648

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-08-14 21:19 UTC, shubham-pampattiwar approved these changes

2023-08-15 06:34 UTC, blackpiglet commented
Looks good, but suggest putting this PR on hold until release-1.12 is cut.

2023-08-16 00:09 UTC, kaovilai requested changes

2023-08-16 00:09 UTC, kaovilai commented on changelogs/unreleased/6649-sseago
> +Deal with PartiallyFailed orphaned backups as well as Completed ones
```suggestion
Delete PartiallyFailed orphaned backups as well as Completed ones
```

2023-08-21 09:13 UTC, blackpiglet commented
@sseago 
release-1.12 was cut. We can continue with this task.

2023-08-21 16:03 UTC, shubham-pampattiwar submitted a review, later dismissed

2023-08-22 07:07 UTC, blackpiglet approved these changes

2023-09-06 20:36 UTC, kaovilai commented
Can we change PR title to "Delete PartiallyFailed orphaned backups as well as Completed ones" ?

2023-10-06 17:35 UTC, shubham-pampattiwar approved these changes

2023-10-06 17:35 UTC, merged