restore: Use warning when Create IsAlreadyExist and Get error
vmware-tanzu/velero pull request #7004
Opened 2023-10-23 17:29 UTC by kaovilai

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-10-23 17:56 UTC, sseago submitted a review, later dismissed

2023-10-23 19:37 UTC, kaovilai commented
whoops changelog in wrong location

2023-10-23 22:53 UTC, sseago approved these changes

2023-10-24 13:06 UTC, weshayutin approved these changes
Thanks @kaovilai

2023-10-25 11:56 UTC, shubham-pampattiwar submitted a review, later dismissed

2023-10-30 07:23 UTC, reasonerjt commented on pkg/restore/restore.go
> +			ctx.log.Warnf("Unable to retrieve in-cluster version of %s: %v, object won't have restore labels", kube.NamespaceAndName(obj), err)
Another impact is `ExistingPolicy` will be skipped for this resource, is this expected?

After this change the behavior is not as described as in the comment in line1527-1530, please also update the comments.

2023-10-30 07:24 UTC, reasonerjt requested changes
Please make sure the behavior described in the comment remains accurate after the code change.

2023-10-31 19:04 UTC, kaovilai commented
will cherry-pick to 1.11 and 1.12 once merged

2023-11-02 02:33 UTC, reasonerjt approved these changes
lgtm

2023-11-02 19:53 UTC, sseago approved these changes

2023-11-02 19:53 UTC, merged