Fix config maps -> configmaps.
vmware-tanzu/velero pull request #7107
Opened 2023-11-16 01:41 UTC by yanggangtony

Thank you for contributing to Velero!

# Please add a summary of your change

Fix config maps -> configmaps.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2023-11-16 01:42 UTC, yanggangtony commented
/kind changelog-not-required

2023-11-16 12:50 UTC, mateusoliveira43 requested changes
Following https://velero.io/docs/v1.12/style-guide/#use-camel-case-for-api-objects the changes should be to "ConfigMaps", instead of "configmaps"

2023-11-16 13:35 UTC, yanggangtony commented
<img width="1313" alt="image" src="https://github.com/vmware-tanzu/velero/assets/12080746/1068bb0b-a902-425f-b56d-030b11d44e09">

@mateusoliveira43 
Thanks for review.

[https://velero.io/docs/v1.12/style-guide/#use-camel-case-for-api-objects](https://velero.io/docs/v1.12/style-guide/#use-camel-case-for-api-objects) , as that ,the secrets should be Secrets?

2023-11-17 02:01 UTC, blackpiglet approved these changes

2023-11-17 12:04 UTC, mateusoliveira43 approved these changes

2023-11-20 06:48 UTC, merged