Reduce backup DeepCopy
vmware-tanzu/velero pull request #7254
Opened 2024-01-02 03:34 UTC by learner0810

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2024-01-03 06:39 UTC, qiuming-best approved these changes

2024-01-08 07:09 UTC, blackpiglet requested changes
The Velero team is working on the v1.13 release branch cut.
Put this PR on hold for now. Will revisit this PR when v1.13 release is ready.

2024-01-09 15:50 UTC, sseago approved these changes
Approved, but holding for release-1.13 branch creation

2024-01-17 07:00 UTC, blackpiglet approved these changes

2024-01-17 11:33 UTC, learner0810 commented
> The Velero team is working on the v1.13 release branch cut. Put this PR on hold for now. Will revisit this PR when v1.13 release is ready.



> ** ** requested changes

Can you manually merge this PR or cancel the requested changes?  thanks ！

2024-01-17 13:41 UTC, merged

2024-01-17 13:41 UTC, blackpiglet commented
@learner0810 
Merged. Thanks.