Add detail for parameter s3ForcePathStyle in MinIO page.
vmware-tanzu/velero pull request #7304
Opened 2024-01-11 04:28 UTC by blackpiglet

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2024-01-11 06:03 UTC, ywk253100 submitted a review, later dismissed

2024-01-11 07:44 UTC, allenxu404 approved these changes

2024-01-11 10:11 UTC, kaovilai requested changes

2024-01-11 10:11 UTC, kaovilai commented on site/content/docs/main/contributions/minio.md
> +    * Please make sure to set parameter `s3ForcePathStyle=true`. The parameter is used to set the Velero integrated AWS SDK data query address style. There are two types of the address: [virtual-host
```suggestion
    * Please make sure to set parameter `s3ForcePathStyle=true`. The parameter is used to set the Velero integrated AWS SDK data query address style. There are two types of the address: [virtual-host and path-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html). If the `s3ForcePathStyle=true` is not set, the default value is false, then the AWS SDK will query in virtual-host style, but the MinIO server only support path-style address by default. The miss match will mean Velero can upload data to MinIO, but **cannot download from MinIO**. This [link](https://github.com/vmware-tanzu/velero/issues/7268) is an example of this issue.
```

2024-01-11 10:11 UTC, kaovilai commented on site/content/docs/v1.13/contributions/minio.md
> +    * Please make sure to set parameter `s3ForcePathStyle=true`. The parameter is used to set the Velero integrated AWS SDK data query address style. There are two types of the address: [virtual-host
```suggestion
    * Please make sure to set parameter `s3ForcePathStyle=true`. The parameter is used to set the Velero integrated AWS SDK data query address style. There are two types of the address: [virtual-host and path-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html). If the `s3ForcePathStyle=true` is not set, the default value is false, then the AWS SDK will query in virtual-host style, but the MinIO server only support path-style address by default. The miss match will mean Velero can upload data to MinIO, but **cannot download from MinIO**. This [link](https://github.com/vmware-tanzu/velero/issues/7268) is an example of this issue.
```

2024-01-11 13:49 UTC, mateusoliveira43 commented
Is this PR needed? Is not the docs built from main branch, and in there, documentation for 1.13 is up to date?

2024-01-11 15:00 UTC, blackpiglet commented
> Is this PR needed? Is not the docs built from main branch, and in there, documentation for 1.13 is up to date?

That's true. It's not required.

2024-01-12 08:55 UTC, blackpiglet commented on site/content/docs/main/contributions/minio.md
> +    * Please make sure to set parameter `s3ForcePathStyle=true`. The parameter is used to set the Velero integrated AWS SDK data query address style. There are two types of the address: [virtual-host
Modified.

2024-01-12 13:48 UTC, kaovilai approved these changes

2024-01-15 04:23 UTC, ywk253100 approved these changes

2024-01-15 04:52 UTC, qiuming-best approved these changes

2024-01-15 05:31 UTC, merged