organize golangci workflow
vmware-tanzu/velero pull request #7595
Opened 2024-03-29 19:49 UTC by mmorel-35

# Please add a summary of your change

* check out before go setup 
* use go version from go.mod
* define output format in golangci 

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2024-03-29 20:20 UTC, kaovilai commented
conflicts with https://github.com/vmware-tanzu/velero/pull/7194

2024-03-30 13:06 UTC, mateusoliveira43 approved these changes
I can rebase my PR afterwards

2024-03-31 12:18 UTC, kaovilai approved these changes

2024-04-01 03:06 UTC, blackpiglet approved these changes

2024-04-01 13:02 UTC, blackpiglet submitted a review, later dismissed

2024-04-15 20:18 UTC, kaovilai approved these changes

2024-04-17 04:08 UTC, anshulahuja98 commented
CI failed due to throttling, rerunning it.

2024-04-18 03:12 UTC, kaovilai approved these changes

2024-04-18 03:52 UTC, anshulahuja98 submitted a review, later dismissed

2024-04-18 06:38 UTC, blackpiglet requested changes
I suggest not to change the configuration file name.
I'm trying to use `golangci/golangci-lint-action@v4` to replace the `make lint` in the lint action.
And the GitHub action cannot find files those names start with `.`.

2024-04-18 07:41 UTC, blackpiglet commented
> .golangci.yaml is one of the default file handled by golangci-lint so you won't need to customize the golangci config file, it will work out of the box, I can complete this PR to package it if you want ?

Please take a view of this commit. 
https://github.com/vmware-tanzu/velero/pull/7697/commits/abb1140c201a03124399f5f232da11919a242138

The linter's output is not formatted if it doesn't pass the configuration file parameter.
If the configuration file parameter is specified, the action always complains ".golangci.yaml" cannot be found.

2024-04-20 10:40 UTC, blackpiglet submitted a review, later dismissed

2024-04-22 09:10 UTC, blackpiglet commented on .github/workflows/pr-linter-check.yml
> +        go-version-file: 'go.mod'
Great. That would be very helpful.

2024-04-22 09:17 UTC, blackpiglet approved these changes

2024-04-22 09:18 UTC, blackpiglet commented on .github/workflows/pr-linter-check.yml
> +        go-version-file: 'go.mod'
Sure.

2024-05-01 16:28 UTC, kaovilai approved these changes

2024-05-05 19:26 UTC, kaovilai approved these changes

2024-05-14 02:19 UTC, blackpiglet submitted a review, later dismissed

2024-05-14 02:21 UTC, blackpiglet commented
We need the maintainers' approval to merge the PR.
Involve more people to accelerate the process.

2024-05-15 02:18 UTC, blackpiglet approved these changes

2024-05-15 15:54 UTC, sseago approved these changes

2024-05-16 03:31 UTC, merged