testifylint: enable error-nil rule
vmware-tanzu/velero pull request #7670
Opened 2024-04-14 19:43 UTC by mmorel-35

# Please add a summary of your change

testifylint: enable error-nil rule

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2024-04-15 07:17 UTC, blackpiglet requested changes
v1.14.0 FC is not far away. Suggest to put on hold of this PR until release-1.14 branch is cut.

2024-05-06 05:31 UTC, blackpiglet commented
@mmorel-35 
The branch cut should happen this May.

2024-05-20 19:59 UTC, kaovilai approved these changes

2024-05-27 03:16 UTC, blackpiglet commented
@mmorel-35 
Could you help to resolve the conflict?

2024-05-27 05:56 UTC, blackpiglet approved these changes

2024-07-16 07:47 UTC, blackpiglet submitted a review, later dismissed

2024-07-16 15:19 UTC, blackpiglet approved these changes

2024-07-16 16:23 UTC, sseago approved these changes

2024-07-16 16:23 UTC, merged