Fix #8168 - AWS secrets should not be exposed while running tests
vmware-tanzu/velero pull request #8169
Opened 2024-08-30 15:13 UTC by mpryc

Thank you for contributing to Velero!

# Please add a summary of your change

Changed the tests to use mocked function that will not read actual secrets from env variables nor AWS config file that may be on the system that is running tests.

As a second guard against exposed secrets comparison for the values does not shows the actual values for the AWS data. This is to prevent situation where programming error may still allow the test to read AWS config/env variables instead of using mocked function.

This change also fixes the test run on the system with AWS creds where the test was failing.

# Does your change fix a particular issue?

Fixes #8168 8168

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

2024-08-30 15:14 UTC, mpryc commented
/kind changelog-not-required

2024-08-30 17:00 UTC, kaovilai reviewed
Made an attempt at simplifying [here](https://github.com/mpryc/velero/pull/1) WDYT?
No mocking, less complicated compares.

2024-08-30 17:30 UTC, mpryc commented
> Made an attempt at simplifying [here](https://github.com/mpryc/velero/pull/1) WDYT? No mocking, less complicated compares.

this won't solve problem where test is ran on the system where some `AWS` configs are defined, e.g. before sending PR:

```shell
$ cd pkg/repository/config/
$ export AWS_ACCESS_KEY_ID=exposed_creds
$ go test ./...


$ cat ~/.aws/credentials 
[default]
aws_access_key_id = exposed_key
aws_secret_access_key = exposed_access_key
$ go test ./...
```

2024-08-30 17:40 UTC, kaovilai commented
We should make unit tests not read from local credentials at all IMO.

2024-08-30 18:05 UTC, kaovilai approved these changes

2024-08-30 18:42 UTC, mpryc commented
As discussed offline on Slack with @kaovilai there may be an issue with running tests in parallel with this proposed change.

The `TB.SetEnv` function disables the test to run in parallel as written in the https://go-review.googlesource.com/c/go/+/260577.

I would like to know if that is an issue here?

2024-08-31 02:14 UTC, kaovilai commented
probably not an issue. [When Setenv is used, isEnvSet is true](https://go-review.googlesource.com/c/go/+/260577/12/src/testing/testing.go#1108), and [any call to t.Parallel() after will panic](https://go-review.googlesource.com/c/go/+/260577/12/src/testing/testing.go#1062).
```
	if t.isEnvSet {
		panic("testing: t.Parallel called after t.Setenv; cannot set environment variables in parallel tests")
	}
```

When we make tests more parallel we'll figure it out then. This is still an enhancement from before.. better an enhancement than no enhancement.

2024-08-31 15:11 UTC, mpryc commented
@kaovilai I could first check if those vars are set and only then use them, how about that? This will mitigate the problem a bit because in the container run scenario it should never execute TB.SetEnv

2024-08-31 15:32 UTC, kaovilai commented
These are internal to go testing package and the check is already done for you if you check the link

2024-09-03 20:35 UTC, kaovilai commented
please fix lint

2024-09-03 20:35 UTC, kaovilai requested changes
lint test fails

2024-09-04 14:51 UTC, kaovilai approved these changes

2024-09-04 18:25 UTC, shubham-pampattiwar approved these changes

2024-11-18 12:33 UTC, reasonerjt approved these changes

2024-11-18 12:34 UTC, merged