Added tracking for deleted namespace status check in restore flow
vmware-tanzu/velero pull request #8233
Opened 2024-09-20 08:40 UTC by sangitaray2021

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

2024-09-20 09:38 UTC, anshulahuja98 commented
For - #8234

2024-09-20 13:19 UTC, kaovilai requested changes
Please add changelog and run linter.

2024-09-23 07:34 UTC, reasonerjt commented
Given we've reached FC and this may impact the restore flow, let's hold this one until the branch is cut for v1.15

2024-09-26 09:03 UTC, anshulahuja98 commented
@kaovilai can you help review the PR?

2024-09-26 14:16 UTC, kaovilai reviewed
IIUC from reviewing, this change reduce potential duplicate `await on if namespace exists (wait for 10 min polling)` to just one instance per restore. Is that correct?

It's not meant to add polling until deletion is complete to resume some other process?

2024-09-30 03:20 UTC, sangitaray2021 commented
> IIUC from reviewing, this change reduce potential duplicate `await on if namespace exists (wait for 10 min polling)` to just one instance per restore. Is that correct?
> 
> It's not meant to add polling until deletion is complete to resume some other process?

yes thats correct. We are reducing duplicate wait by caching the namespace which is under deletion.

2024-09-30 15:11 UTC, kaovilai commented on pkg/util/kube/namespace_deletionstatus_tracker.go
> +}
Why are there both ns and name parameters?
What purpose does that serve other than duplicate value params?

Is this interface meant to be more generic? Perhaps `namespaceDeletionStatusTrackerKey(ns, name)` was meant to be more like `resourceDeletionStatusTrackerKey(resource, ns, name string) string` ?

2024-10-30 16:11 UTC, kaovilai approved these changes
lgtm

2024-10-30 16:11 UTC, kaovilai commented on pkg/util/kube/resource_deletionstatus_tracker.go
> +// resourceDeletionStatusTracker keeps track of in-progress backups.
```suggestion
// resourceDeletionStatusTracker keeps track of items pending deletion blocking in-progress backups.
```

2024-11-01 09:55 UTC, anshulahuja98 commented on pkg/util/kube/resource_deletionstatus_tracker.go
> +// resourceDeletionStatusTracker keeps track of in-progress backups.
@sangitaray2021, please add this also.

2024-11-01 09:57 UTC, anshulahuja98 commented on pkg/util/kube/utils.go
> +			return false, nsCreated, err
let's make this error more verbose. 
Something like - Skipping polling for terminating namespace.

2024-11-08 09:36 UTC, anshulahuja98 approved these changes

2024-11-15 07:52 UTC, reasonerjt commented
@anshulahuja98 I don't quite understand the background of the problem.  I'm asking Xun @blackpiglet to take a look as he used to have discussion around this topic.

2024-11-15 08:30 UTC, blackpiglet commented
Per my understanding, this PR tracks the namespace hanging in the terminating state.
If the namespace already hits a timeout during the restore, it is added to the tracked, and a flag is marked as true.
If there is a second time meeting the same timeout issue for the namespace, the restore is marked as failed.

IMO, revoking the ongoing restore is the ideal solution for this issue, but that obviously needs more effort, so I think this is also an acceptable solution for now.

2024-11-18 04:53 UTC, anshulahuja98 commented
@blackpiglet can you signoff if the PR looks good?

2024-11-18 06:54 UTC, blackpiglet approved these changes

2024-11-18 08:11 UTC, merged